[[AMGCL_C]]
arch = "aarch64"
git-tree-sha1 = "c99c6b7f9701b46f6d057a453e3abd54281df0c2"
os = "macos"

    [[AMGCL_C.download]]
    sha256 = "6776950567c378d19f42191729fc13a61fa8f0a3b03e7bda5a8ba9cad92bb901"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.2.0+0/AMGCL_C.v0.2.0.aarch64-apple-darwin.tar.gz"
[[AMGCL_C]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9753a4c185b66f91a9352001c89bee09da3542b5"
libc = "glibc"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "0b9c2cfcc0728d52d6cb6310c44a6ea9049c6ff0548571cc8d30729cf565b4c9"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.2.0+0/AMGCL_C.v0.2.0.aarch64-linux-gnu-cxx03.tar.gz"
[[AMGCL_C]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f05dd472c897b456ca15f30f842d04b0b647644a"
libc = "glibc"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "ad475573e83691c565f1e1db9cbf67d12a6f593fffb932e794bbd509afb34a28"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.2.0+0/AMGCL_C.v0.2.0.aarch64-linux-gnu-cxx11.tar.gz"
[[AMGCL_C]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f498acdb7d35d3ffe0fccb073630a3751760f89e"
libc = "musl"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "616f877e4c90576ea55a10c125c48cdd050594e7d35b508a0c689afe1cbf737f"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.2.0+0/AMGCL_C.v0.2.0.aarch64-linux-musl-cxx03.tar.gz"
[[AMGCL_C]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e2a0992e14b4238786cfed26e484dd715923f754"
libc = "musl"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "f34c1c456647c8309854dbc1526bd99afa750150fca1dac0f11ab16b25b6363a"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.2.0+0/AMGCL_C.v0.2.0.aarch64-linux-musl-cxx11.tar.gz"
[[AMGCL_C]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "34a98577a0a6d6f4d278c4ac9544815bdd0ac472"
libc = "glibc"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "9e2f44c9139782a8efa0452a2664580b5fcb9281522aeb8df572bee4720c133b"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.2.0+0/AMGCL_C.v0.2.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[AMGCL_C]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a408d24e92626a994d0165804af3b5cf4d18f5c4"
libc = "glibc"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "7c76019a8aff09c585d7c10c0957f307508384556f531e38d3d4147dd82ac35b"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.2.0+0/AMGCL_C.v0.2.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[AMGCL_C]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "638dd327372b1d055a4460e2721d11e3b287a3f7"
libc = "musl"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "404c6113764b6c895ad582d5476acdfd87626d27766ad7ddb9bc334b6fb2337e"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.2.0+0/AMGCL_C.v0.2.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[AMGCL_C]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "df67e787b01c6181bd049c956d234b5f0d6b84d2"
libc = "musl"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "b69e243238b7904602aa06e0e8dc801c67a510e7002d6b17b073c309b366c839"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.2.0+0/AMGCL_C.v0.2.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[AMGCL_C]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eba5e45bd74e9b20f3049939d1c28ffcec7498df"
libc = "glibc"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "ac96ab893be2d6febdca733bc6b8d61a4636e428323d91f4f609774b5c631172"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.2.0+0/AMGCL_C.v0.2.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[AMGCL_C]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dd2ff16f621c9f56cced83b496e78d743be2fc1c"
libc = "glibc"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "498cdadd40598e7dd35c07f6c7c8b73520df1a34e86f51e98178984fcd3b8cd2"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.2.0+0/AMGCL_C.v0.2.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[AMGCL_C]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4f1aa1ac024a2b722cb60b8f14727c11b08299c0"
libc = "musl"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "b5d897b1469b0d0d349e28ecb95c3281ccf18ad155fd028f78c14883df0e42f8"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.2.0+0/AMGCL_C.v0.2.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[AMGCL_C]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b8f93e0a4f9e6cce3ea29aa474bb3849f79a3d6d"
libc = "musl"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "6218d6890186fd047af8e6c2bae146c23da9ff14e5f20fe520bc9276252f8a58"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.2.0+0/AMGCL_C.v0.2.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[AMGCL_C]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0c224a6a9dddc1fcd07b0e59d825dfdffb644ab7"
libc = "glibc"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "d54c00fa305c5e371f7c374478489a7c90333cc389e4ca57b1b71c31fea74f96"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.2.0+0/AMGCL_C.v0.2.0.i686-linux-gnu-cxx03.tar.gz"
[[AMGCL_C]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7bea312c6e7fe5af7bea4ed2692bd8f7f8ad2f12"
libc = "glibc"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "5d2db2cfba3cb872525b5c9f02d4a692b9c17e0d52c3065d3d675279bf6a8948"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.2.0+0/AMGCL_C.v0.2.0.i686-linux-gnu-cxx11.tar.gz"
[[AMGCL_C]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d7822a11607b941cd6ab7ba567005d1364408648"
libc = "musl"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "28463c3265334685b4a4ebbb1ecd03fb6100feb9eefb56eedefd3f6c4a46cdac"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.2.0+0/AMGCL_C.v0.2.0.i686-linux-musl-cxx03.tar.gz"
[[AMGCL_C]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1abeb23b1e52172558da0ed3efa832653db8f3b"
libc = "musl"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "50a6fcca19ba0609fa9e0bf9f1604b9519d591012f1de6513ef6eaa519e3e28e"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.2.0+0/AMGCL_C.v0.2.0.i686-linux-musl-cxx11.tar.gz"
[[AMGCL_C]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "37d5c1b332ad8039f42344195f26e08dac8cab86"
os = "windows"

    [[AMGCL_C.download]]
    sha256 = "11c7a67268f3759324bc5677573f4cabd48fe343a7a3e3635890dc04561f358e"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.2.0+0/AMGCL_C.v0.2.0.i686-w64-mingw32-cxx03.tar.gz"
[[AMGCL_C]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e82c95ee646cc9ea4f52e5fe1d67a6d98d164bda"
os = "windows"

    [[AMGCL_C.download]]
    sha256 = "e54314b7e39df456d7d1d35d92f8e31da387d6beeaa33341bd1d8b2972640e38"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.2.0+0/AMGCL_C.v0.2.0.i686-w64-mingw32-cxx11.tar.gz"
[[AMGCL_C]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c2b015a13917d383e284aa28f6cbb93d20d2a4c2"
libc = "glibc"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "35f5045d7d1b6079e8ce8e2825cd7d84246f34ee8573aa9fce2048df366b555f"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.2.0+0/AMGCL_C.v0.2.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[AMGCL_C]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6971c6ead01e88ce81078f86a20adcae5d98c02a"
libc = "glibc"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "bac408404a404b1c314ccd6904e81b6a06244633e38b26d60e6ced24f7584349"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.2.0+0/AMGCL_C.v0.2.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[AMGCL_C]]
arch = "x86_64"
git-tree-sha1 = "dd31a70e2bcf15dc499fbe93cb9c0dfb80b6bbd2"
os = "macos"

    [[AMGCL_C.download]]
    sha256 = "c03da98142f0515b340c72f519a4f1a1310d27511b150fa7de731ee61de1e33c"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.2.0+0/AMGCL_C.v0.2.0.x86_64-apple-darwin.tar.gz"
[[AMGCL_C]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "87d7e5851246ef07e45d17d74c2b9fb8300df189"
libc = "glibc"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "ca9f2c2f28260bbf0c308d78dd90ca9ad54bc13bd28e711e2b85f0cbe71567d0"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.2.0+0/AMGCL_C.v0.2.0.x86_64-linux-gnu-cxx03.tar.gz"
[[AMGCL_C]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "61eb504443d86f72bedfafa827d2bffd34651b81"
libc = "glibc"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "0da71083a1433765b7625153a7f40621caf8c3626b63fda6c877fcb17a393e28"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.2.0+0/AMGCL_C.v0.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[AMGCL_C]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "74fdc9e7fc1d9269a31557ac957b278a4efba64c"
libc = "musl"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "65ecc41f812359c86ccac9454e8985c1ee3432a64483d4327d83a53d58d23993"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.2.0+0/AMGCL_C.v0.2.0.x86_64-linux-musl-cxx03.tar.gz"
[[AMGCL_C]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "62f4f31e1f5bb42b84e8d6aa4004be036ec35064"
libc = "musl"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "3d676d20220183da186f06ff3025b393ff3f27335d7a8205adc68fc36f957f7d"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.2.0+0/AMGCL_C.v0.2.0.x86_64-linux-musl-cxx11.tar.gz"
[[AMGCL_C]]
arch = "x86_64"
git-tree-sha1 = "dbd0f80257c58e748cd1f45e35a65f6cb5315678"
os = "freebsd"

    [[AMGCL_C.download]]
    sha256 = "2f106a9fa60d17fff28cdec194731c3d73badc21098740c7fa4e959e5ac64685"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.2.0+0/AMGCL_C.v0.2.0.x86_64-unknown-freebsd.tar.gz"
[[AMGCL_C]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "002ae1cafc74f5fb4d81cf66037cb257d19dedb6"
os = "windows"

    [[AMGCL_C.download]]
    sha256 = "5a3b5e4cba6ba82067f7cbc438babf06fbff73adb2ae0dd9e2f6a878fe90aeb8"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.2.0+0/AMGCL_C.v0.2.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[AMGCL_C]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2f1f6cf4d857c38fb803409c52b06198f61baad1"
os = "windows"

    [[AMGCL_C.download]]
    sha256 = "c24d6b990ddfb63848a9c17e6a068bdedccee94a7bb8462959eb3dfc0d730cd1"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.2.0+0/AMGCL_C.v0.2.0.x86_64-w64-mingw32-cxx11.tar.gz"
