[[AMGCL_C]]
arch = "aarch64"
git-tree-sha1 = "c8a69429baa07bfee8b1a17829799777d7e8ba87"
os = "macos"

    [[AMGCL_C.download]]
    sha256 = "1b7aae3686a446df8dafa87c0a9a37024a46cba64e3bfea9174d6adafad32a3f"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.1.2+0/AMGCL_C.v0.1.2.aarch64-apple-darwin.tar.gz"
[[AMGCL_C]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3dca8ea1f2df770c0781f289f7f328c37c97a068"
libc = "glibc"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "922b526c88c921e69987bc0254f44cee2ef74676fc17fbbdd8669372555dd6d5"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.1.2+0/AMGCL_C.v0.1.2.aarch64-linux-gnu-cxx03.tar.gz"
[[AMGCL_C]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b4f1d3a10826016dd14808e87cee2d7a3b3decef"
libc = "glibc"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "6484a8ed0bae767f293b760791af31fae0ac75a9709774296563446626c1e1ab"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.1.2+0/AMGCL_C.v0.1.2.aarch64-linux-gnu-cxx11.tar.gz"
[[AMGCL_C]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a721cec3cdfc71f97747bb142b2b6cd06a9f61a6"
libc = "musl"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "b5fa2cef1e75de0c9ce1c33bc7f486b04fee1e9ece9be267fa0b4a75977e48bd"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.1.2+0/AMGCL_C.v0.1.2.aarch64-linux-musl-cxx03.tar.gz"
[[AMGCL_C]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fec79c3c602c47d2a5369105d07bb53872d6258e"
libc = "musl"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "05b3dafd2ff4090cceab617fbd9714ac1b71c3bd89a4aa0930d0c910037cced4"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.1.2+0/AMGCL_C.v0.1.2.aarch64-linux-musl-cxx11.tar.gz"
[[AMGCL_C]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dc8da735c4a31ceb0b65ce31b3722cda51e4d2a2"
libc = "glibc"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "455ce8ff7ff6d5347fca52915f0e38d3b78b8d70af849fb6a17ac7e27a4d37d0"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.1.2+0/AMGCL_C.v0.1.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[AMGCL_C]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "96b0552e8a1d6db32e6fbfa29df6ebdd676021df"
libc = "glibc"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "28271080f3c1fa5c52dffedaa4b64aff8198016bae6217b08ed3484f77a12a3c"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.1.2+0/AMGCL_C.v0.1.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[AMGCL_C]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c1b24441853fa91211d9f52e8a20ffd18acc814"
libc = "musl"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "fd4ea84692cbb3bffc8d712b4d92a67ab0f7b44e9c8b484275d064a6324bba13"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.1.2+0/AMGCL_C.v0.1.2.armv6l-linux-musleabihf-cxx03.tar.gz"
[[AMGCL_C]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9aa50795d3e9ada4cfc77b9e1ac4d1d2ccdb5fd4"
libc = "musl"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "56a662cf584b792422047dddc92eb56a5db7474565b004d2cf5e42c292825120"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.1.2+0/AMGCL_C.v0.1.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[AMGCL_C]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "41278b5b7c2cc5d5bb1550b2b5b9300780e97a73"
libc = "glibc"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "36b5a6880f40b25a8d257dc1f854aba0a52fca23af6acd4e54fa057c3b5ab102"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.1.2+0/AMGCL_C.v0.1.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[AMGCL_C]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d9a1255faac0ae2cb6a9af0d5e67ea95dc38eda"
libc = "glibc"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "73f460aa1f7574f53dc2009b506e6ab878d379082980f22fb6cd21bf4128ebba"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.1.2+0/AMGCL_C.v0.1.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[AMGCL_C]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "adf2c272a229b3dafe0264fd479c5d6ea40a4b5b"
libc = "musl"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "04aca83e22c191e859772731cecad3ec8bd8782cf6f875308d7be3c6ad5c8c94"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.1.2+0/AMGCL_C.v0.1.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[AMGCL_C]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c2d250b5710ed4f976bfafce26238dba033a9126"
libc = "musl"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "58a607328293f306938ae28745b23ccc2b2bec611580f9901a5c30fc63414dfd"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.1.2+0/AMGCL_C.v0.1.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[AMGCL_C]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "08721585d2acd44927cb4b858d28d9d751fc7c91"
libc = "glibc"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "0e79b8b0a4c7eb0ac974594209e3677d59cd63687402d5d1f70a7e9e8d914a37"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.1.2+0/AMGCL_C.v0.1.2.i686-linux-gnu-cxx03.tar.gz"
[[AMGCL_C]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "620860deed3a2bfa0d4776e66c075694651f03fb"
libc = "glibc"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "5530b5df65faa833a642d29ad162618468a7a213ddb9faa26ebceeb147945e95"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.1.2+0/AMGCL_C.v0.1.2.i686-linux-gnu-cxx11.tar.gz"
[[AMGCL_C]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "95d78b3ff167d9b8b7379f97b466504fb038b283"
libc = "musl"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "e2d2849989e36fadcb953130d40fc208361e07e2c59c38e25516ffa9e9208e5d"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.1.2+0/AMGCL_C.v0.1.2.i686-linux-musl-cxx03.tar.gz"
[[AMGCL_C]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "10ff80d2d4cfbca2868394380b9a0fb92b9c4be1"
libc = "musl"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "fb91edf90a003956a80760cd0d336cf267a2a62e5e53577aa54fcaf5f5639cc0"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.1.2+0/AMGCL_C.v0.1.2.i686-linux-musl-cxx11.tar.gz"
[[AMGCL_C]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "de4358a8d28a213a4ce6383c15f3a224c1ee7874"
os = "windows"

    [[AMGCL_C.download]]
    sha256 = "83a4a3a5254e8d6c1f3b0a7120d7b7827d28450284f82c96fabbe97e76ba4551"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.1.2+0/AMGCL_C.v0.1.2.i686-w64-mingw32-cxx03.tar.gz"
[[AMGCL_C]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c3d32e100ad447e279c03b8fdb2cd15d09a7558"
os = "windows"

    [[AMGCL_C.download]]
    sha256 = "f9d9ed77713e58f12f3c7e4ee2e140a9c07b1e5743eee32406ac8899d70e1385"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.1.2+0/AMGCL_C.v0.1.2.i686-w64-mingw32-cxx11.tar.gz"
[[AMGCL_C]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5b6ab073ed960d0b768fcfe7b9c4ba77694ae39c"
libc = "glibc"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "d1c6526dfb58f1162c6fafb7e75a6f4184dfe98a58e4759a200a9fbc4acdd502"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.1.2+0/AMGCL_C.v0.1.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[AMGCL_C]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3656b46dbe26d302fa18390528598b893f29d8f9"
libc = "glibc"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "bb282a1e8c806d8697ad4f7a75666ac488f9038f78ad9c3f661205ee9d519483"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.1.2+0/AMGCL_C.v0.1.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[AMGCL_C]]
arch = "x86_64"
git-tree-sha1 = "63521a65dfe54e9d2368b9452e3b12951dd61cc7"
os = "macos"

    [[AMGCL_C.download]]
    sha256 = "62957c472a2cb9beb0607c11d5788cfb38dbb28e9fbf4e9d174731ba48374a63"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.1.2+0/AMGCL_C.v0.1.2.x86_64-apple-darwin.tar.gz"
[[AMGCL_C]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a3ec4f04bee684438fd58f14a907218abd0f2554"
libc = "glibc"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "e20014d5e1e4a31eb4732b6bbd4320f26adf767b9f5c4df3ba170ec386ee9c8b"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.1.2+0/AMGCL_C.v0.1.2.x86_64-linux-gnu-cxx03.tar.gz"
[[AMGCL_C]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "17472373ab8d6163c7c616098e80dab6d0e49021"
libc = "glibc"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "43fa4f9e3de099ad0cdfac37e7da8e8bfad128d051de69a5363dba75c9507d00"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.1.2+0/AMGCL_C.v0.1.2.x86_64-linux-gnu-cxx11.tar.gz"
[[AMGCL_C]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "007b0d7820653183b85a10aa7d216573e6814838"
libc = "musl"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "51888256e7b5806fed23e6d75cea19589493f5f4ee89a51f754f1ebfc4754970"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.1.2+0/AMGCL_C.v0.1.2.x86_64-linux-musl-cxx03.tar.gz"
[[AMGCL_C]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "61409f847506deaa3b6326bed9a9d07743805ab4"
libc = "musl"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "ba9c6fb04ae8e653680a1c83f9f833882bedfe4a19f0c8efe4dd96921e182043"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.1.2+0/AMGCL_C.v0.1.2.x86_64-linux-musl-cxx11.tar.gz"
[[AMGCL_C]]
arch = "x86_64"
git-tree-sha1 = "b2d2fe01d48f69d193c2ced013c1f0943321c7bf"
os = "freebsd"

    [[AMGCL_C.download]]
    sha256 = "ff1d4077b7874eec8a6ae8529227d83be70acea97bd7b6aa7841a2c16a75c889"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.1.2+0/AMGCL_C.v0.1.2.x86_64-unknown-freebsd.tar.gz"
[[AMGCL_C]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e23a1c12ba65892ce98b672ad57bf5c09870d553"
os = "windows"

    [[AMGCL_C.download]]
    sha256 = "b5d2c15333fae593e9787df0d04954dc3a36b0175bcbbec6987c3a30387f8303"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.1.2+0/AMGCL_C.v0.1.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[AMGCL_C]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "133079545e0343eb3215ab0de454c1f0c7d96daf"
os = "windows"

    [[AMGCL_C.download]]
    sha256 = "45cb57ef1d5b9a4fc36c1f96c9a28a0a3d4d202138448cf4feb36ff49fff375b"
    url = "https://github.com/JuliaBinaryWrappers/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.1.2+0/AMGCL_C.v0.1.2.x86_64-w64-mingw32-cxx11.tar.gz"
